language: node_js
node_js:
  - "node"
before_install:
  - npm install eslint -g
  - npm install eslint-config-standard -g
  - npm install eslint-plugin-import -g
  - npm install eslint-plugin-node -g
  - npm install eslint-plugin-promise -g
  - npm install eslint-plugin-standard -g
install:
  - npm install
before_script:
  - "npm run eslint"
script:
  - npm test
